// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/my-trips": {
    params: {};
  };
  "/plan": {
    params: {};
  };
  "/trip/:id": {
    params: {
      "id": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/my-trips" | "/plan" | "/trip/:id" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./my-trips/page.jsx": {
    id: "my-trips/page";
    page: "/my-trips";
  };
  "./plan/page.jsx": {
    id: "plan/page";
    page: "/plan";
  };
  "./trip/[id]/page.jsx": {
    id: "trip/[id]/page";
    page: "/trip/:id";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};